version: "2"

services:

  web:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - .:/code
      - ./docker/config/site.conf:/etc/nginx/conf.d/default.conf

  php:
    image: php:7.2-fpm
    user: "${UID}:${GID}"
    volumes:
      - .:/code

  mysql:
    image: mysql:5.7
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: track_share
      MYSQL_USER: track_share
      MYSQL_PASSWORD: tracksRus
